urls.py
from django.urls import path

from . import views

app_name = "kanban"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/<int:status>", views.update, name="update"),
    path("<int:pk>/", views.HistoryView.as_view(), name="history"),
    path("new_card", views.new_card, name="new_card"),
    path("new_note/<int:task>", views.new_card, name="new_note"),
]

models.py
from django.db import models
from django import forms

int_to_status = {
    0: "create",
    1: "backlog",
    2: "design",
    3: "write",
    4: "review",
    5: "testing",
    6: "done",
    7: "hidden",
    8: "In Progress",
}


# Create your models here.


class Task(models.Model):

    Choices = []
    for ii in int_to_status:
        Choices.append((ii, int_to_status[ii].upper()))
    title = models.CharField(max_length=250, null=False, blank=False)
    status = models.IntegerField(choices=Choices, default=1)
    def __str__(self):
        return "{} :{}".format(self.title, int_to_status[self.status])


    def save(self, *args, **kwargs):
        a = self.taskupdate_set.order_by("-time")
        if a:
            if self.status not in int_to_status:
                raise ValueError("status not in appropiate range of {}".format(int_to_status))
                return
            if self.status == a[0].new_status:
                super(Task, self).save(*args, **kwargs)
                return

            b = TaskUpdate(old_status=a[0].new_status, new_status=self.status, task= self)
        else:
            b = TaskUpdate(old_status=0, new_status=self.status, task=self)
        super(Task, self).save(*args, **kwargs)
        b.save()
        return


class TaskUpdate(models.Model):
    class Meta:
        ordering = ['-time']
    Choices = []
    for ii in int_to_status:
        Choices.append((ii, int_to_status[ii].upper()))
    old_status = models.IntegerField(choices=Choices)
    new_status = models.IntegerField(choices=Choices)
    time = models.DateTimeField(auto_now=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return "{} -> {}".format(self.task.title, int_to_status[self.old_status], int_to_status[self.new_status])


class TaskNote(models.Model):
    class Meta:
        ordering = ['-time']
    Choices = []
    for ii in int_to_status:
        Choices.append((ii, int_to_status[ii].upper()))
    status = models.IntegerField(choices=Choices)
    time = models.DateTimeField(auto_now=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    note = models.TextField(blank=False)

    def __str__(self):
        return "{} ({}|{}): {}".format(self.task.title, int_to_status[self.status], self.time, self.note)

forms.py
from .models import Task, TaskUpdate
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from django import forms


class CardForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title"]

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ["title", "status"]

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('status'),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'save')),
                )
            )

views.py
from django.shortcuts import render
from .models import Task, TaskUpdate, TaskNote
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy, reverse
from django.db import transaction
from . import forms as app_forms
from django.views import generic
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect

# Create your views here.

def update(request, pk, status):
    task = get_object_or_404(Task, pk=pk)
    task.status = status
    task.save()
    return HttpResponseRedirect(reverse("kanban:index"))


class IndexView(generic.ListView):
    form = app_forms.CardForm()
    template_name = "kanban/directory.html"
    context_object_name = "task_list"

    def get_queryset(self):
        return Task.objects.all()


class NewTask(CreateView):
    model = Task
    template_name = "Polls/question_create.html"
    form_class = app_forms.TaskForm
    success_url = None

    def form_invalid(self, form):
        print("fail")
        return reverse_lazy('Polls:vote', kwargs={'pk': self.object.pk})


    def form_valid(self, form):
        with transaction.atomic():
            form.instance.created_by = self.request.user
            self.object = form.save()
            create_recipt = TaskUpdate(task=self.object, old_status=0, new_status=1)
            create_recipt.save()
        return super(NewTask, self).form_valid(form)

    def get_success_url(self):
        print("sucess")
        return reverse_lazy('Polls:details', kwargs={'pk': self.object.pk})


class HistoryView(generic.DetailView):
    model = Task
    template_name = "kanban/history.html"

    def get_queryset(self):
        return Task.objects.all()

def new_card(request):
    if request.method == "POST":
        a = Task(title=request.POST["task_title"])
        a.save()
    return HttpResponseRedirect(reverse("kanban:index"))

def new_card(request, task):
    if request.method == "POST":
        otask = get_object_or_404(Task, pk=task)
        note = TaskNote(status=otask.status, task=otask, note=request.POST["note"])
        note.save()
    print(task)
    return HttpResponseRedirect(reverse("kanban:history", args=(task,)))

templates/kanban/create_task.html
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="card">
    <div class="card-header">
      Create Task
    </div>
    <div class="card-body">
      {% crispy form %}
    </div>
  </div>
</div>
<p id="demo">shits same</p>
{% endblock content %}

templates/kanban/directory.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kanban/directory.css' %}">
<body>
<h1>Kanban Board</h1>
 <form action="{% url 'kanban:new_card' %}" method="post">
   {% csrf_token %}
   <p>
     <input type="text" name="task_title" size = "60">
     <button type="submit">New Card</button>
   </p>
  </form>
{% if task_list %}
<div class="board">
  <div class="backlog">
    <h3>Backlog</h3>
    <ul>
      {% for task in task_list %}
        {% if task.status == 1 %}
          <div class="backlog_card">
            <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
            <p><a href="{% url 'kanban:update' task.pk 2 %}">To Code design</a></p>
            <p><a href="{% url 'kanban:update' task.pk 8 %}">To Tasking</a></p>
          </div>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
  <div class="WIP">
    <h2>Code WIP</h2>
    <div class="code_WIP">
      <div class="design">
        <h3>Design</h3>
        <ul>
          {% for task in task_list %}
            {% if task.status == 2 %}
              <div class="design_card">
                <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
                <p><a href="{% url 'kanban:update' task.pk 1 %}">Re-Requested</a></p>
                <p><a href="{% url 'kanban:update' task.pk 3 %}">Write</a></p>
              </div>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      <div class="write">
        <h3>Writing</h3>
        <ul>
          {% for task in task_list %}
            {% if task.status == 3 %}
              <div class="write_card">
                <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
                <p><a href="{% url 'kanban:update' task.pk 2 %}">Re-Design</a></p>
                <p><a href="{% url 'kanban:update' task.pk 4 %}">Review</a></p>
              </div>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      <div class="review">
        <h3>In Review</h3>
        <ul>
          {% for task in task_list %}
            {% if task.status == 4 %}
              <div class="review_card">
                <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
                <p><a href="{% url 'kanban:update' task.pk 3 %}">Re-Write</a></p>
                <p><a href="{% url 'kanban:update' task.pk 5 %}">Testing</a></p>
              </div>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      <div class="testing">
        <h3>Testing</h3>
        <ul>
          {% for task in task_list %}
            {% if task.status == 5 %}
              <div class="testing_card">
                <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
                <p><a href="{% url 'kanban:update' task.pk 3 %}">Re-Write</a></p>
                <p><a href="{% url 'kanban:update' task.pk 6 %}">Complete</a></p>
              </div>
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
    <h2>Tasking</h2>
    <div class="TODOing">
      <h3>In Progress</h3>
        {% for task in task_list %}
          {% if task.status == 8 %}
            <div class="TODO_card">
              <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
              <p><a href="{% url 'kanban:update' task.pk 1 %}">Back to Backlog</a></p>
              <p><a href="{% url 'kanban:update' task.pk 6 %}">Complete</a></p>
            </div>
        {% endif %}
        {% endfor %}
    </div>
  </div>
  <div class="complete">
    <h3>Completed</h3>
    <ul>
      {% for task in task_list %}
        {% if task.status == 6 %}
          <div class="complete_card">
            <h4><a href="{% url 'kanban:history' task.pk %}">{{ task.title }}</h4>
            <p><a href="{% url 'kanban:update' task.pk 1 %}">Request</a></p>
            <p><a href="{% url 'kanban:update' task.pk 3 %}">Re-Write</a></p>
            <p><a href="{% url 'kanban:update' task.pk 7 %}">hide Item</a></p>
          </div>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

{% else %}
  <p>No Tasks are available.</p>
{% endif %}
</body>

templates/kanban/history.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kanban/history.css' %}">
<body>

  <h1>{{ task.title }}</h1>

  <form action="{% url 'kanban:new_note' task.pk %}" method="post">
    {% csrf_token %}
    <p>
      <textarea name="note" rows="6" cols="70"></textarea>
      <button type="submit">New Note</button>
    </p>
  </form>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  {% if task.tasknote_set.all %} <h3>Notes</h3> {% endif %}
  {% for note in task.tasknote_set.all %}
  <li>{{  note.note }} <p>{{ note.time}}</p></li>
  {% endfor %}
  <h3>History</h3>
  {% for update in task.taskupdate_set.all %}
    <li>{{ update }} Completed on: {{update.time}}</li>
  {% endfor %}
  <p><a href="{% url 'kanban:index' %}">Back to the Board</a></p>
</body>